#!/usr/bin/bash

#start swwww
swww query || swww init

wallpaper_dir="$HOME/.config/hypr/wallpapers"

if [[ -d "$wallpaper_dir" ]]; then
    # Create an array of image files in the wallpaper directory
    images=("$wallpaper_dir"/*)
    # Get a random index within the array size
    random_index=$((RANDOM % ${#images[@]}))
    # Get the randomly selected image
    random_image="${images[random_index]}"

    if [[ -f "$random_image" && ! -L "$random_image" ]]; then
        # Set the desktop wallpaper using your existing command
        swww img "$random_image"
    else
        swww img ~/.config/hypr/wallpaper.jpg
    fi

else
    swww img ~/.config/hypr/wallpaper.jpg
fi
