#!/usr/bin/bash

swayidle -w \
    timeout 300 'swaylock -f' \
    timeout 600 'hyprctl --batch "dpms off" ; if [ "$(acpi -a | grep Adapter | cut -d: -f2 | xargs)" = "off-line" ]; then systemctl suspend; fi' \
    resume 'hyprctl --batch "dpms on"' \
    before-sleep 'swaylock -f'
