#!/usr/bin/bash

swayidle -w \
    timeout 300 'swaylock -f' \
    timeout 600 'hyprctl --batch "dpms off" ; systemctl suspend' \
    resume 'hyprctl --batch "dpms on"' \
    before-sleep 'swaylock -f'
