#!/bin/bash

iDIR="${HOME}/.config/hypr/icons"

# Get Volume
get_volume() {
    volume=$(pamixer --get-volume)
    echo "$volume"
}

# Get volume icons
get_vol_icon() {
    is_mute=$1
    if [ "${is_mute}" == "mute" ]; then
        echo "$iDIR/volume-muted.png"; exit
    fi

    if [ "${is_mute}" == "unmute" ]; then
        echo "$iDIR/volume-high.png"; exit
    fi

    current=$(get_volume)
    if [[ "$current" -eq "0" ]]; then
        echo "$iDIR/volume-muted.png"
    elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
        echo "$iDIR/volume-low.png"
    elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
        echo "$iDIR/volume-medium.png"
    elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
        echo "$iDIR/volume-high.png"
    fi
}

# Get mic icons
get_mic_icon() {
    is_mute=$1
    if [ "${is_mute}" == "true" ]; then echo "$iDIR/microphone-muted.png"; exit; fi

    current=$(pamixer --default-source --get-volume)
    if [[ "$current" -eq "0" ]]; then
        echo "$iDIR/microphone-muted.png"
        # elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
        #     echo "$iDIR/microphone.png"
        # elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
        #     echo "$iDIR/microphone.png"
        # elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
    else
        echo "$iDIR/microphone.png"
    fi
}

# Notify
notify_user() {
    mpv ~/.config/hypr/sounds/cork.mp3 & \
        notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_vol_icon)" "Volume" "$(get_volume) %"
}

# Increase Volume
inc_volume() {
    if [ "$(pamixer --get-mute)" == "true" ]; then
        pamixer -u
    fi
    pamixer -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
    pamixer -d 5 && notify_user
}

# Toggle Mute
toggle_vol_mute() {
    if [ "$(pamixer --get-mute)" == "false" ]; then
        pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_vol_icon 'mute')" "Volume" "Switched OFF"
    elif [ "$(pamixer --get-mute)" == "true" ]; then
        pamixer -u && \
            mpv ~/.config/hypr/sounds/cork.mp3 & \
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_vol_icon 'unmute')" "Volume" "Switched ON"
    fi
}

# Toggle Mic
toggle_mic_mute() {
    if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
        pamixer --default-source -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon 'true')" "Microphone" "Switched OFF"
    elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
        pamixer -u --default-source u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon)" "Microphone" "Switched ON"
    fi
}

# Notify
notify_mic_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon)" "Microphone" "$(pamixer --default-source --get-volume) %"
}

# Increase MIC Volume
inc_mic_volume() {
    pamixer --default-source -i 5 && notify_mic_user
}

# Decrease MIC Volume
dec_mic_volume() {
    pamixer --default-source -d 5 && notify_mic_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_vol_mute
elif [[ "$1" == "--toggle-mic" ]]; then
    toggle_mic_mute
elif [[ "$1" == "--get-icon" ]]; then
    get_vol_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
    get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
    inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
    dec_mic_volume
else
    get_volume
fi
